/* VERSION: 1.1.21 */
/*
 https://github.com/es-shims/es5-shim
 @license es5-shim Copyright 2009-2015 by contributors, MIT License
 see https://github.com/es-shims/es5-shim/blob/master/LICENSE
*/
(function(t){function c(a){if(d[a])return d[a].a;var b=d[a]={ib:a,Da:!1,a:{}};t[a].call(b.a,b,b.a,c);b.Da=!0;return b.a}var d={};c.jb=t;c.ma=d;c.B=function(a,b){c.O(a)||Object.defineProperty(a,"a",{configurable:!1,enumerable:!0,get:b})};c.za=function(a){var b=a&&a.ab?function(){return a["default"]}:function(){return a};c.B(b,b);return b};c.O=function(a){return Object.prototype.hasOwnProperty.call(a,"a")};c.hb="dist";return c(c.lb=82)})({13:function(t){t.a={get:function(c,d){"undefined"===typeof d&&
(d=null);var a=document.cookie;c+="=";var b=a.indexOf("; "+c);if(-1==b){if(b=a.indexOf(c))return d}else b+=2;d=document.cookie.indexOf(";",b);-1==d&&(d=a.length);return decodeURIComponent(a.substring(b+c.length,d))},set:function(c,d,a,b){var x=new Date;b=b||"domain";var h="/";d?(a=x.getTime()+6E4*a,"session"==b&&(a=0)):a=x.getTime()-1;a&&(a=(new Date(a)).toGMTString());"page"==b&&(h="");c=c+"="+encodeURIComponent(d);h&&(c+="; path="+h);a&&(c+="; expires="+a);document.cookie=c}}},14:function(t,c,d){var a=
d(13),b={sa:43200,pa:function(a){function b(){try{m.doScroll("left")}catch(L){setTimeout(b,50);return}c("poll")}function c(b){if("readystatechange"!=b.type||"complete"==k.readyState)("load"==b.type?n:k)[D](p+b.type,c,!1),!d&&(d=!0)&&a.call(n,b.type||b)}var d=!1,x=!0,n=window,k=n.document,m=k.documentElement,F=k.addEventListener,g=F?"addEventListener":"attachEvent",D=F?"removeEventListener":"detachEvent",p=F?"":"on";if("complete"==k.readyState)a.call(n,"lazy");else{if(!F&&m.doScroll){try{x=!n.frameElement}catch(L){}x&&
b()}k[g](p+"DOMContentLoaded",c,!1);k[g](p+"readystatechange",c,!1);n[g](p+"load",c,!1)}},log:function(b){window._sc_dbg&&console.log(b)},Ka:function(){return{w:document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth,h:document.documentElement.clientHeight||window.innerHeight||document.body.clientHeight}},P:function(a){var c=document.getElementById(a);b.log("sizeInfo->blockSize["+a+"]: "+c.offsetWidth+"x"+c.offsetHeight);return{w:c.offsetWidth,h:c.offsetHeight}},v:function(a){var c=
b.Ka();return"sz_"+a+"_"+(window.outerWidth||c.w)},qa:function(c){var d=a.get(b.v(c));b.log("sizeInfo->get by ["+b.v(c)+"] => "+d);if(!d)return d;try{d=JSON.parse(d)}catch(q){return null}return d},ra:function(c,d){b.pa(function(){function h(d){b.log("sizeInfo->set ["+b.v(c)+"] => "+JSON.stringify(d));a.set(b.v(c),JSON.stringify(d),b.sa)}var r=b.P(d);if(r.w&&r.h)return h(r);var x=10,n=setInterval(function(){var a=b.P(d);a.w&&a.h&&h(a);--x||clearInterval(n)},500)})},eb:function(a,c){b.ra(a,c)}};t.a=
b},19:function(t){t.a={encode:function(c){var d="",a,b,x,h,q,r,A=0;c=c.replace(/\r\n/g,"\n");b="";for(x=0;x<c.length;x++)h=c.charCodeAt(x),128>h?b+=String.fromCharCode(h):(127<h&&2048>h?b+=String.fromCharCode(h>>6|192):(b+=String.fromCharCode(h>>12|224),b+=String.fromCharCode(h>>6&63|128)),b+=String.fromCharCode(h&63|128));for(c=b;A<c.length;)a=c.charCodeAt(A++),b=c.charCodeAt(A++),x=c.charCodeAt(A++),h=a>>2,a=(a&3)<<4|b>>4,q=(b&15)<<2|x>>6,r=x&63,isNaN(b)?q=r=64:isNaN(x)&&(r=64),d=d+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(q)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(r);return d},decode:function(c){var d="",a,b,x,h,q,r=0;for(c=c.replace(/[^A-Za-z0-9\+\/\=]/g,"");r<c.length;)a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(r++)),b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(r++)),
h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(r++)),q="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(c.charAt(r++)),a=a<<2|b>>4,b=(b&15)<<4|h>>2,x=(h&3)<<6|q,d+=String.fromCharCode(a),64!=h&&(d+=String.fromCharCode(b)),64!=q&&(d+=String.fromCharCode(x));c=d;d="";for(h=0;h<c.length;)q=c.charCodeAt(h),128>q?(d+=String.fromCharCode(q),h++):191<q&&224>q?(r=c.charCodeAt(h+1),d+=String.fromCharCode((q&31)<<6|r&63),h+=2):(r=c.charCodeAt(h+
1),c3=c.charCodeAt(h+2),d+=String.fromCharCode((q&15)<<12|(r&63)<<6|c3&63),h+=3);return d},S:function(c){return this.encode(c).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")},fb:function(c){return this.decode(c.replace(/\-/g,"+").replace(/_/g,"/")+"==".substring(0,3*c.length%4))}}},48:function(t,c,d){var a,b;(function(x,h){!(a=h,b="function"===typeof a?a.call(c,d,c,t):a,b&&(t.a=b))})(this,function(){function a(e){return null!==e&&"object"===typeof e&&"number"===typeof e.length&&0<=e.length&&
!X(e)&&H(e.callee)}function b(e){return"[object Arguments]"===xa(e)}function c(e){var f=e.constructor;return f&&f.prototype===e}function d(e){for(var f=y.g(this),l=y.f(f.length),E=0;E<arguments.length;)f[l+E]=arguments[E],E+=1;f.length=l+E;return l+E}function A(e){var f=!0,l=!0,E=!1;if(e)try{e.call("foo",function(e,l,E){"object"!==typeof E&&(f=!1)}),e.call([1],function(){l="string"===typeof this},"x")}catch(Eb){E=!0}return!!e&&!E&&f&&l}function n(){}function k(e){var f=typeof e;return null===e||"object"!==
f&&"function"!==f}function m(e){try{var f=ya.call(e).replace(/\/\/.*\n/g,"").replace(/\/\*[.\s\S]*\*\//g,"").replace(/\n/mg," ").replace(/ {2}/g," ");return Ta.test(f)}catch(l){return!1}}var F=Array,g=F.prototype,D=Object,p=D.prototype,L=Function,u=L.prototype,I=String,w=I.prototype,G=Number,T=G.prototype,t=g.slice,za=g.splice,Y=g.push,da=g.unshift,Aa=g.concat,Ua=g.join,C=u.call,ea=u.apply,R=Math.max,Z=Math.min,fa=p.toString,ga="function"===typeof Symbol&&"symbol"===typeof Symbol.toStringTag,H,ya=
Function.prototype.toString,Ta=/^\s*class /;H=function(e){if(!e||"function"!==typeof e&&"object"!==typeof e)return!1;if(ga){var f;try{m(e)?f=!1:(ya.call(e),f=!0)}catch(l){f=!1}return f}if(m(e))return!1;e=fa.call(e);return"[object Function]"===e||"[object GeneratorFunction]"===e};var ha,Va=RegExp.prototype.exec;ha=function(e){if("object"!==typeof e)e=!1;else{var f;if(ga)try{Va.call(e),f=!0}catch(l){f=!1}else f="[object RegExp]"===fa.call(e);e=f}return e};var J,Wa=String.prototype.valueOf;J=function(e){if("string"===
typeof e)e=!0;else if("object"!==typeof e)e=!1;else{var f;if(ga)try{Wa.call(e),f=!0}catch(l){f=!1}else f="[object String]"===fa.call(e);e=f}return e};var ia=D.defineProperty&&function(){try{var e={};D.defineProperty(e,"x",{enumerable:!1,value:e});for(var f in e)return!1;return e.x===e}catch(l){return!1}}(),v=function(e){var f;f=ia?function(e,f,a,b){!b&&f in e||D.defineProperty(e,f,{configurable:!0,enumerable:!1,writable:!0,value:a})}:function(e,f,a,b){!b&&f in e||(e[f]=a)};return function(l,E,a){for(var b in E)e.call(E,
b)&&f(l,b,E[b],a)}}(p.hasOwnProperty),U=G.isNaN||function(e){return e!==e},y={j:function(e){e=+e;U(e)?e=0:e&&e!==1/0&&e!==-(1/0)&&(e=(0<e||-1)*Math.floor(Math.abs(e)));return e},ia:function(e){var f;if(k(e))return e;f=e.valueOf;if(H(f)&&(f=f.call(e),k(f)))return f;f=e.toString;if(H(f)&&(f=f.call(e),k(f)))return f;throw new TypeError;},g:function(e){if(null==e)throw new TypeError("can't convert "+e+" to object");return D(e)},f:function(e){return e>>>0}};v(u,{bind:function(e){var f=this;if(!H(f))throw new TypeError("Function.prototype.bind called on incompatible "+
f);for(var l=t.call(arguments,1),E,a=R(0,f.length-l.length),b=[],c=0;c<a;c++)Y.call(b,"$"+c);E=L("binder","return function ("+Ua.call(b,",")+"){ return binder.apply(this, arguments); }")(function(){if(this instanceof E){var a=ea.call(f,this,Aa.call(l,t.call(arguments)));return D(a)===a?a:this}return ea.call(f,e,Aa.call(l,t.call(arguments)))});f.prototype&&(n.prototype=f.prototype,E.prototype=new n,n.prototype=null);return E}});var O=C.bind(p.hasOwnProperty),xa=C.bind(p.toString),N=C.bind(t),ja=ea.bind(t);
if("object"===typeof document&&document&&document.documentElement)try{N(document.documentElement.childNodes)}catch(e){var Xa=N,Ba=ja,N=function(e){for(var f=[],a=e.length;0<a--;)f[a]=e[a];return Ba(f,Xa(arguments,1))},ja=function(e,l){return Ba(N(e),l)}}var M=C.bind(w.slice),K=C.bind(w.split),Ya=C.bind(w.indexOf),P=C.bind(Y),ka=C.bind(p.propertyIsEnumerable),Ca=C.bind(g.sort),X=F.isArray||function(e){return"[object Array]"===xa(e)},Za=1!==[].unshift(0);v(g,{unshift:function(){da.apply(this,arguments);
return this.length}},Za);v(F,{isArray:X});var Da=D("a"),Q="a"!==Da[0]||!(0 in Da);v(g,{forEach:function(e){var f=y.g(this),l=Q&&J(this)?K(this,""):f,a=-1,b=y.f(l.length),c;1<arguments.length&&(c=arguments[1]);if(!H(e))throw new TypeError("Array.prototype.forEach callback must be a function");for(;++a<b;)a in l&&("undefined"===typeof c?e(l[a],a,f):e.call(c,l[a],a,f))}},!A(g.forEach));v(g,{map:function(e){var f=y.g(this),l=Q&&J(this)?K(this,""):f,a=y.f(l.length),b=F(a),c;1<arguments.length&&(c=arguments[1]);
if(!H(e))throw new TypeError("Array.prototype.map callback must be a function");for(var d=0;d<a;d++)d in l&&(b[d]="undefined"===typeof c?e(l[d],d,f):e.call(c,l[d],d,f));return b}},!A(g.map));v(g,{filter:function(e){var f=y.g(this),l=Q&&J(this)?K(this,""):f,a=y.f(l.length),b=[],c,d;1<arguments.length&&(d=arguments[1]);if(!H(e))throw new TypeError("Array.prototype.filter callback must be a function");for(var g=0;g<a;g++)g in l&&(c=l[g],("undefined"===typeof d?e(c,g,f):e.call(d,c,g,f))&&P(b,c));return b}},
!A(g.filter));v(g,{every:function(e){var f=y.g(this),l=Q&&J(this)?K(this,""):f,a=y.f(l.length),b;1<arguments.length&&(b=arguments[1]);if(!H(e))throw new TypeError("Array.prototype.every callback must be a function");for(var c=0;c<a;c++)if(c in l&&("undefined"===typeof b?!e(l[c],c,f):!e.call(b,l[c],c,f)))return!1;return!0}},!A(g.every));v(g,{some:function(e){var f=y.g(this),l=Q&&J(this)?K(this,""):f,a=y.f(l.length),c;1<arguments.length&&(c=arguments[1]);if(!H(e))throw new TypeError("Array.prototype.some callback must be a function");
for(var b=0;b<a;b++)if(b in l&&("undefined"===typeof c?e(l[b],b,f):e.call(c,l[b],b,f)))return!0;return!1}},!A(g.some));var Ea=!1;g.reduce&&(Ea="object"===typeof g.reduce.call("es5",function(e,f,l,a){return a}));v(g,{reduce:function(e){var f=y.g(this),l=Q&&J(this)?K(this,""):f,a=y.f(l.length);if(!H(e))throw new TypeError("Array.prototype.reduce callback must be a function");if(0===a&&1===arguments.length)throw new TypeError("reduce of empty array with no initial value");var b=0,c;if(2<=arguments.length)c=
arguments[1];else{do{if(b in l){c=l[b++];break}if(++b>=a)throw new TypeError("reduce of empty array with no initial value");}while(1)}for(;b<a;b++)b in l&&(c=e(c,l[b],b,f));return c}},!Ea);var Fa=!1;g.reduceRight&&(Fa="object"===typeof g.reduceRight.call("es5",function(e,f,l,a){return a}));v(g,{reduceRight:function(e){var f=y.g(this),l=Q&&J(this)?K(this,""):f,a=y.f(l.length);if(!H(e))throw new TypeError("Array.prototype.reduceRight callback must be a function");if(0===a&&1===arguments.length)throw new TypeError("reduceRight of empty array with no initial value");
var b,a=a-1;if(2<=arguments.length)b=arguments[1];else{do{if(a in l){b=l[a--];break}if(0>--a)throw new TypeError("reduceRight of empty array with no initial value");}while(1)}if(0>a)return b;do a in l&&(b=e(b,l[a],a,f));while(a--);return b}},!Fa);var $a=g.indexOf&&-1!==[0,1].indexOf(1,2);v(g,{indexOf:function(e){var f=Q&&J(this)?K(this,""):y.g(this),l=y.f(f.length);if(0===l)return-1;var a=0;1<arguments.length&&(a=y.j(arguments[1]));for(a=0<=a?a:R(0,l+a);a<l;a++)if(a in f&&f[a]===e)return a;return-1}},
$a);var ab=g.lastIndexOf&&-1!==[0,1].lastIndexOf(0,-3);v(g,{lastIndexOf:function(e){var f=Q&&J(this)?K(this,""):y.g(this),l=y.f(f.length);if(0===l)return-1;var a=l-1;1<arguments.length&&(a=Z(a,y.j(arguments[1])));for(a=0<=a?a:l-Math.abs(a);0<=a;a--)if(a in f&&e===f[a])return a;return-1}},ab);var bb=function(){var e=[1,2],f=e.splice();return 2===e.length&&X(f)&&!f.length}();v(g,{splice:function(e,f){return arguments.length?za.apply(this,arguments):[]}},!bb);var cb=function(){var e={};g.splice.call(e,
0,0,1);return 1===e.length}();v(g,{splice:function(e,f){if(!arguments.length)return[];var a=arguments;this.length=R(y.j(this.length),0);0<arguments.length&&"number"!==typeof f&&(a=N(arguments),2>a.length?P(a,this.length-e):a[1]=y.j(f));return za.apply(this,a)}},!cb);var db=function(){var e=new F(1E5);e[8]="x";e.splice(1,1);return 7===e.indexOf("x")}(),eb=function(){var e=[];e[256]="a";e.splice(257,0,"b");return"a"===e[256]}();v(g,{splice:function(e,f){for(var a=y.g(this),b=[],c=y.f(a.length),d=y.j(e),
g=0>d?R(c+d,0):Z(d,c),d=Z(R(y.j(f),0),c-g),k=0,p;k<d;)p=I(g+k),O(a,p)&&(b[k]=a[p]),k+=1;var h=N(arguments,2),m=h.length,u;if(m<d){for(var k=g,w=c-d;k<w;)p=I(k+d),u=I(k+m),O(a,p)?a[u]=a[p]:delete a[u],k+=1;k=c;for(p=c-d+m;k>p;)delete a[k-1],--k}else if(m>d)for(k=c-d;k>g;)p=I(k+d-1),u=I(k+m-1),O(a,p)?a[u]=a[p]:delete a[u],--k;k=g;for(g=0;g<h.length;++g)a[k]=h[g],k+=1;a.length=c-d+m;return b}},!db||!eb);var Ga=g.join,aa;try{aa="1,2,3"!==Array.prototype.join.call("123",",")}catch(e){aa=!0}aa&&v(g,{join:function(e){e=
"undefined"===typeof e?",":e;return Ga.call(J(this)?K(this,""):this,e)}},aa);v(g,{join:function(e){return Ga.call(this,"undefined"===typeof e?",":e)}},!0);var fb=function(){var e={};return 1!==Array.prototype.push.call(e,void 0)||1!==e.length||"undefined"!==typeof e[0]||!O(e,0)}();v(g,{push:function(e){return X(this)?Y.apply(this,arguments):d.apply(this,arguments)}},fb);var gb=function(){var e=[];return 1!==e.push(void 0)||1!==e.length||"undefined"!==typeof e[0]||!O(e,0)}();v(g,{push:d},gb);v(g,{slice:function(e,
f){var a=J(this)?K(this,""):this;return ja(a,arguments)}},Q);var la;a:{try{[1,2].sort(null)}catch(e){try{[1,2].sort({})}catch(f){la=!1;break a}}la=!0}var ma;a:{try{[1,2].sort(/a/);ma=!1;break a}catch(e){}ma=!0}var na;a:{try{[1,2].sort(void 0);na=!0;break a}catch(e){}na=!1}v(g,{sort:function(e){if("undefined"===typeof e)return Ca(this);if(!H(e))throw new TypeError("Array.prototype.sort callback must be a function");return Ca(this,e)}},la||!na||!ma);var hb=!ka({toString:null},"toString"),ib=ka(function(){},
"prototype"),jb=!O("x","0"),kb={Ya:!0,La:!0,Sa:!0,Ta:!0,Na:!0,Pa:!0,Oa:!0,Va:!0,Wa:!0,Ma:!0,Xa:!0,Qa:!0,Ua:!0,Ra:!0},lb=function(){if("undefined"===typeof window)return!1;for(var e in window)try{!kb["$"+e]&&O(window,e)}catch(f){return!0}return!1}(),Ha="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),mb=Ha.length,Ia=b(arguments)?b:a;v(D,{keys:function(e){var f=H(e),a=Ia(e),b=null!==e&&"object"===typeof e,d=b&&J(e);if(!b&&!f&&!a)throw new TypeError("Object.keys called on a non-object");
b=[];f=ib&&f;if(d&&jb||a)for(d=0;d<e.length;++d)P(b,I(d));if(!a)for(var g in e)f&&"prototype"===g||!O(e,g)||P(b,I(g));if(hb){var k;if("undefined"!==typeof window&&lb)try{k=c(e)}catch(Fb){k=!1}else k=c(e);for(a=0;a<mb;a++)g=Ha[a],k&&"constructor"===g||!O(e,g)||P(b,g)}return b}});var nb=D.keys&&function(){return 2===D.keys(arguments).length}(1,2),ob=D.keys&&function(){var e=D.keys(arguments);return 1!==arguments.length||1!==e.length||1!==e[0]}(1),Ja=D.keys;v(D,{keys:function(e){return Ia(e)?Ja(N(e)):
Ja(e)}},!nb||ob);var ba=!!(new Date(-0xc782b5b342b24)).getUTCMonth(),ca=new Date(-0x55d318d56a724),Ka=new Date(14496624E5),pb="Mon, 01 Jan -45875 11:59:59 GMT"!==ca.toUTCString(),oa,pa;-720>ca.getTimezoneOffset()?(oa="Tue Jan 02 -45875"!==ca.toDateString(),pa=!/^Thu Dec 10 2015 \d\d:\d\d:\d\d GMT[-+]\d\d\d\d(?: |$)/.test(String(Ka))):(oa="Mon Jan 01 -45875"!==ca.toDateString(),pa=!/^Wed Dec 09 2015 \d\d:\d\d:\d\d GMT[-+]\d\d\d\d(?: |$)/.test(String(Ka)));var qa=C.bind(Date.prototype.getFullYear),
ra=C.bind(Date.prototype.getMonth),sa=C.bind(Date.prototype.getDate),V=C.bind(Date.prototype.getUTCFullYear),W=C.bind(Date.prototype.getUTCMonth),ta=C.bind(Date.prototype.getUTCDate),qb=C.bind(Date.prototype.getUTCDay),La=C.bind(Date.prototype.getUTCHours),Ma=C.bind(Date.prototype.getUTCMinutes),Na=C.bind(Date.prototype.getUTCSeconds),rb=C.bind(Date.prototype.getUTCMilliseconds),ua="Sun Mon Tue Wed Thu Fri Sat".split(" "),va="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");v(Date.prototype,
{getFullYear:function(){if(!(this&&this instanceof Date))throw new TypeError("this is not a Date object.");var e=qa(this);return 0>e&&11<ra(this)?e+1:e},getMonth:function(){if(!(this&&this instanceof Date))throw new TypeError("this is not a Date object.");var e=qa(this),f=ra(this);return 0>e&&11<f?0:f},getDate:function(){if(!(this&&this instanceof Date))throw new TypeError("this is not a Date object.");var e=qa(this),f=ra(this),a=sa(this);return 0>e&&11<f?12===f?a:sa(new Date(e+1,0,0))-a+1:a},getUTCFullYear:function(){if(!(this&&
this instanceof Date))throw new TypeError("this is not a Date object.");var e=V(this);return 0>e&&11<W(this)?e+1:e},getUTCMonth:function(){if(!(this&&this instanceof Date))throw new TypeError("this is not a Date object.");var e=V(this),a=W(this);return 0>e&&11<a?0:a},getUTCDate:function(){if(!(this&&this instanceof Date))throw new TypeError("this is not a Date object.");var e=V(this),a=W(this),b=ta(this);return 0>e&&11<a?12===a?b:sa(new Date(e+1,0,0))-b+1:b}},ba);v(Date.prototype,{toUTCString:function(){if(!(this&&
this instanceof Date))throw new TypeError("this is not a Date object.");var e=qb(this),a=ta(this),b=W(this),c=V(this),d=La(this),g=Ma(this),k=Na(this);return ua[e]+", "+(10>a?"0"+a:a)+" "+va[b]+" "+c+" "+(10>d?"0"+d:d)+":"+(10>g?"0"+g:g)+":"+(10>k?"0"+k:k)+" GMT"}},ba||pb);v(Date.prototype,{toDateString:function(){if(!(this&&this instanceof Date))throw new TypeError("this is not a Date object.");var e=this.getDay(),a=this.getDate(),b=this.getMonth(),c=this.getFullYear();return ua[e]+" "+va[b]+" "+
(10>a?"0"+a:a)+" "+c}},ba||oa);if(ba||pa)Date.prototype.toString=function(){if(!(this&&this instanceof Date))throw new TypeError("this is not a Date object.");var e=this.getDay(),a=this.getDate(),b=this.getMonth(),c=this.getFullYear(),d=this.getHours(),g=this.getMinutes(),k=this.getSeconds(),p=this.getTimezoneOffset(),m=Math.floor(Math.abs(p)/60),u=Math.floor(Math.abs(p)%60);return ua[e]+" "+va[b]+" "+(10>a?"0"+a:a)+" "+c+" "+(10>d?"0"+d:d)+":"+(10>g?"0"+g:g)+":"+(10>k?"0"+k:k)+" GMT"+(0<p?"-":"+")+
(10>m?"0"+m:m)+(10>u?"0"+u:u)},ia&&D.defineProperty(Date.prototype,"toString",{configurable:!0,enumerable:!1,writable:!0});var sb=Date.prototype.toISOString&&-1===(new Date(-621987552E5)).toISOString().indexOf("-000001"),tb=Date.prototype.toISOString&&"1969-12-31T23:59:59.999Z"!==(new Date(-1)).toISOString(),ub=C.bind(Date.prototype.getTime);v(Date.prototype,{toISOString:function(){if(!isFinite(this)||!isFinite(ub(this)))throw new RangeError("Date.prototype.toISOString called on non-finite value.");
for(var e=V(this),a=W(this),e=e+Math.floor(a/12),a=[(a%12+12)%12+1,ta(this),La(this),Ma(this),Na(this)],e=(0>e?"-":9999<e?"+":"")+M("00000"+Math.abs(e),0<=e&&9999>=e?-4:-6),b=0;b<a.length;++b)a[b]=M("00"+a[b],-2);return e+"-"+N(a,0,2).join("-")+"T"+N(a,2).join(":")+"."+M("000"+rb(this),-3)+"Z"}},sb||tb);(function(){try{return Date.prototype.toJSON&&null===(new Date(NaN)).toJSON()&&-1!==(new Date(-621987552E5)).toJSON().indexOf("-000001")&&Date.prototype.toJSON.call({toISOString:function(){return!0}})}catch(e){return!1}})()||
(Date.prototype.toJSON=function(){var a=D(this),f=y.ia(a);if("number"===typeof f&&!isFinite(f))return null;f=a.toISOString;if(!H(f))throw new TypeError("toISOString property is not callable");return f.call(a)});var vb=1E15===Date.parse("+033658-09-27T01:46:40.000Z"),wb=!isNaN(Date.parse("2012-04-04T24:00:00.500Z"))||!isNaN(Date.parse("2012-11-31T23:59:59.000Z"))||!isNaN(Date.parse("2012-12-31T23:59:60.000Z"));if(isNaN(Date.parse("2000-01-01T00:00:00.000Z"))||wb||!vb){var S=Math.pow(2,31)-1,Oa=U((new Date(1970,
0,1,0,0,0,S+1)).getTime());Date=function(a){function e(a,e){var b=1<e?1:0;return d[e]+Math.floor((a-1969+b)/4)-Math.floor((a-1901+b)/100)+Math.floor((a-1601+b)/400)+365*(a-1970)}function b(e,f,c,d,l,g,p){var m=arguments.length;if(this instanceof a){var u=g,h=p;if(Oa&&7<=m&&p>S)var w=Math.floor(Math.floor(p/S)*S/1E3),u=u+w,h=h-1E3*w;m=1===m&&I(e)===e?new a(b.parse(e)):7<=m?new a(e,f,c,d,l,u,h):6<=m?new a(e,f,c,d,l,u):5<=m?new a(e,f,c,d,l):4<=m?new a(e,f,c,d):3<=m?new a(e,f,c):2<=m?new a(e,f):1<=m?
new a(e instanceof a?+e:e):new a}else m=a.apply(this,arguments);k(m)||v(m,{constructor:b},!0);return m}var c=/^(\d{4}|[+-]\d{6})(?:-(\d{2})(?:-(\d{2})(?:T(\d{2}):(\d{2})(?::(\d{2})(?:(\.\d{1,}))?)?(Z|(?:([-+])(\d{2}):(\d{2})))?)?)?)?$/,d=[0,31,59,90,120,151,181,212,243,273,304,334,365],g;for(g in a)O(a,g)&&(b[g]=a[g]);v(b,{now:a.now,UTC:a.UTC},!0);b.prototype=a.prototype;v(b.prototype,{constructor:b},!0);v(b,{parse:function(f){var b=c.exec(f);if(b){var d=G(b[1]),l=G(b[2]||1)-1,g=G(b[3]||1)-1,k=G(b[4]||
0),m=G(b[5]||0),p=G(b[6]||0),u=Math.floor(1E3*G(b[7]||0)),h=!(!b[4]||b[8]),w="-"===b[9]?1:-1,q=G(b[10]||0),b=G(b[11]||0);return k<(0<m||0<p||0<u?24:25)&&60>m&&60>p&&1E3>u&&-1<l&&12>l&&24>q&&60>b&&-1<g&&g<e(d,l+1)-e(d,l)&&(d=60*(24*(e(d,l)+g)+k+q*w),d=1E3*(60*(d+m+b*w)+p)+u,h&&(m=0,p=d,Oa&&p>S&&(u=Math.floor(Math.floor(p/S)*S/1E3),m+=u,p-=1E3*u),d=G(new a(1970,0,1,0,0,m,p))),-864E13<=d&&864E13>=d)?d:NaN}return a.parse.apply(this,arguments)}});return b}(Date)}Date.now||(Date.now=function(){return(new Date).getTime()});
var xb=T.toFixed&&("0.000"!==(8E-5).toFixed(3)||"1"!==(.9).toFixed(0)||"1.25"!==(1.255).toFixed(2)||"1000000000000000128"!==(0xde0b6b3a7640080).toFixed(0)),z={D:1E7,size:6,data:[0,0,0,0,0,0],multiply:function(a,b){for(var e=-1;++e<z.size;)b+=a*z.data[e],z.data[e]=b%z.D,b=Math.floor(b/z.D)},I:function(a){for(var e=z.size,b=0;0<=--e;)b+=z.data[e],z.data[e]=Math.floor(b/a),b=b%a*z.D},X:function(){for(var a=z.size,b="";0<=--a;)if(""!==b||!a||0!==z.data[a])var c=I(z.data[a]),b=""===b?c:b+(M("0000000",
0,7-c.length)+c);return b},pow:function f(a,b,c){return 0===b?c:1===b%2?f(a,b-1,c*a):f(a*a,b/2,c)},log:function(a){for(var b=0;4096<=a;)b+=12,a/=4096;for(;2<=a;)b+=1,a/=2;return b}};v(T,{toFixed:function(a){var b,c,f;a=G(a);a=U(a)?0:Math.floor(a);if(0>a||20<a)throw new RangeError("Number.toFixed called with invalid number of decimals");b=G(this);if(U(b))return"NaN";if(-1E21>=b||1E21<=b)return I(b);c="";0>b&&(c="-",b=-b);f="0";if(1E-21<b)if(f=z.log(b*z.pow(2,69,1))-69,b=0>f?b*z.pow(2,-f,1):b/z.pow(2,
f,1),b*=4503599627370496,f=52-f,0<f){z.multiply(0,b);for(b=a;7<=b;)z.multiply(1E7,0),b-=7;z.multiply(z.pow(10,b,1),0);for(b=f-1;23<=b;)z.I(8388608),b-=23;z.I(1<<b);z.multiply(1,1);z.I(2);f=z.X()}else z.multiply(0,b),z.multiply(1<<-f,0),f=z.X()+M("0.00000000000000000000",2,2+a);0<a?(b=f.length,f=b<=a?c+M("0.0000000000000000000",0,a-b+2)+f:c+M(f,0,b-a)+"."+M(f,b-a)):f=c+f;return f}},xb);var wa;try{wa="1"===(1).toPrecision(void 0)}catch(f){wa=!0}var Pa=T.toPrecision;v(T,{toPrecision:function(a){return"undefined"===
typeof a?Pa.call(this):Pa.call(this,a)}},wa);2!=="ab".split(/(?:ab)*/).length||4!==".".split(/(.?)(.?)/).length||"t"==="tesst".split(/(s)*/)[1]||4!=="test".split(/(?:)/,-1).length||"".split(/.?/).length||1<".".split(/()()/).length?function(){var a="undefined"===typeof/()??/.exec("")[1],b=Math.pow(2,32)-1;w.split=function(f,c){var d=String(this);if("undefined"===typeof f&&0===c)return[];if(!ha(f))return K(this,f,c);var g=[],k=(f.ignoreCase?"i":"")+(f.multiline?"m":"")+(f.tb?"u":"")+(f.rb?"y":""),m=
0,p,l,u;f=new RegExp(f.source,k+"g");a||(p=new RegExp("^"+f.source+"$(?!\\s)",k));k="undefined"===typeof c?b:y.f(c);for(l=f.exec(d);l;){c=l.index+l[0].length;if(c>m&&(P(g,M(d,m,l.index)),!a&&1<l.length&&l[0].replace(p,function(){for(var a=1;a<arguments.length-2;a++)"undefined"===typeof arguments[a]&&(l[a]=void 0)}),1<l.length&&l.index<d.length&&Y.apply(g,N(l,1)),u=l[0].length,m=c,g.length>=k))break;f.lastIndex===l.index&&f.lastIndex++;l=f.exec(d)}m===d.length?!u&&f.test("")||P(g,""):P(g,M(d,m));return g.length>
k?N(g,0,k):g}}():"0".split(void 0,0).length&&(w.split=function(a,b){return"undefined"===typeof a&&0===b?[]:K(this,a,b)});var Qa=w.replace;(function(){var a=[];"x".replace(/x(.)?/g,function(b,f){P(a,f)});return 1===a.length&&"undefined"===typeof a[0]})()||(w.replace=function(a,b){var c=H(b),f=ha(a)&&/\)[*?]/.test(a.source);return c&&f?Qa.call(this,a,function(c){var f=arguments.length,d=a.lastIndex;a.lastIndex=0;var g=a.exec(c)||[];a.lastIndex=d;P(g,arguments[f-2],arguments[f-1]);return b.apply(this,
g)}):Qa.call(this,a,b)});var yb=w.substr,zb="".substr&&"b"!=="0b".substr(-1);v(w,{substr:function(a,b){var c=a;0>a&&(c=R(this.length+a,0));return yb.call(this,c,b)}},zb);var Ab=/^[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff][\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff]*/,Bb=/[\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff][\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff]*$/,
Cb=w.trim&&("\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff".trim()||!"\u200b".trim());v(w,{trim:function(){if("undefined"===typeof this||null===this)throw new TypeError("can't convert "+this+" to object");return I(this).replace(Ab,"").replace(Bb,"")}},Cb);var Ra=C.bind(String.prototype.trim);v(w,{lastIndexOf:function(a){if("undefined"===typeof this||null===this)throw new TypeError("can't convert "+this+" to object");
for(var b=I(this),c=I(a),f=1<arguments.length?G(arguments[1]):NaN,f=U(f)?Infinity:y.j(f),f=Z(R(f,0),b.length),d=c.length,g=f+d;0<g;){var g=R(0,g-d),k=Ya(M(b,g,f+d),c);if(-1!==k)return g+k}return-1}},w.lastIndexOf&&!1);var Db=w.lastIndexOf;v(w,{lastIndexOf:function(a){return Db.apply(this,arguments)}},1!==w.lastIndexOf.length);if(8!==parseInt("\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff08")||22!==parseInt("\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff0x16"))parseInt=
function(a){var b=/^[-+]?0[xX]/;return function(c,f){"symbol"===typeof c&&""+c;c=Ra(String(c));f=G(f)||(b.test(c)?16:10);return a(c,f)}}(parseInt);-Infinity!==1/-0&&(parseFloat=function(a){return function(b){b=Ra(String(b));var c=a(b);return c||"-"!==M(b,0,1)?c:-0}}(parseFloat));"RangeError: test"!==String(new RangeError("test"))&&(Error.prototype.toString=function(){if("undefined"===typeof this||null===this)throw new TypeError("can't convert "+this+" to object");var a=this.name;"undefined"===typeof a?
a="Error":"string"!==typeof a&&(a=I(a));var b=this.message;"undefined"===typeof b?b="":"string"!==typeof b&&(b=I(b));return a?b?a+": "+b:a:b});if(ia){var Sa=function(a){var b=Error.prototype;if(ka(b,a)){var c=Object.getOwnPropertyDescriptor(b,a);c.configurable&&(c.enumerable=!1,Object.defineProperty(b,a,c))}};Sa("message");""!==Error.prototype.message&&(Error.prototype.message="");Sa("name")}"/a/gim"!==String(/a/mig)&&(RegExp.prototype.toString=function(){var a="/"+this.source+"/";this.global&&(a+=
"g");this.ignoreCase&&(a+="i");this.multiline&&(a+="m");return a})})},49:function(t,c,d){t=this;c=d(50);d=d(51);c.H=d.H;c.L=d.L;t.a=c},50:function(t,c){(function(c){function a(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var b=A[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function b(c,d){var k,g,m=q,p,h=d[c];h&&"object"===typeof h&&"function"===typeof h.toJSON&&(h=h.toJSON(c));"function"===typeof n&&(h=n.call(d,c,h));switch(typeof h){case "string":return a(h);
case "number":return isFinite(h)?String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";q+=r;p=[];if("[object Array]"===Object.prototype.toString.apply(h)){g=h.length;for(c=0;c<g;c+=1)p[c]=b(c,h)||"null";d=p.length?q?"[\n"+q+p.join(",\n"+q)+"\n"+m+"]":"["+p.join(",")+"]":"[]";q=m;return d}if(n&&"object"===typeof n)for(g=n.length,c=0;c<g;c+=1)"string"===typeof n[c]&&(k=n[c],(d=b(k,h))&&p.push(a(k)+(q?": ":":")+d));else for(k in h)Object.prototype.hasOwnProperty.call(h,
k)&&(d=b(k,h))&&p.push(a(k)+(q?": ":":")+d);d=p.length?q?"{\n"+q+p.join(",\n"+q)+"\n"+m+"}":"{"+p.join(",")+"}":"{}";q=m;return d}}var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,q,r,A={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},n;"function"!==typeof c.stringify&&(c.stringify=
function(a,c,d){var g;r=q="";if("number"===typeof d)for(g=0;g<d;g+=1)r+=" ";else"string"===typeof d&&(r=d);if((n=c)&&"function"!==typeof c&&("object"!==typeof c||"number"!==typeof c.length))throw Error("JSON.stringify");return b("",{"":a})});"function"!==typeof c.parse&&(c.parse=function(a,b){function c(a,d){var g,k,h=a[d];if(h&&"object"===typeof h)for(g in h)Object.prototype.hasOwnProperty.call(h,g)&&(k=c(h,g),void 0!==k?h[g]=k:delete h[g]);return b.call(a,d,h)}a=String(a);d.lastIndex=0;d.test(a)&&
(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return a=eval("("+a+")"),"function"===typeof b?c({"":a},""):a;throw new SyntaxError("JSON.parse");})})(c)},51:function(t,c){(function(c){"function"!==typeof c.H&&(c.H=function(a){var b=[],c=[];return function q(a,d){var n,
k,m;switch(typeof a){case "object":if(!a)return null;for(n=0;n<b.length;n+=1)if(b[n]===a)return{M:c[n]};b.push(a);c.push(d);if("[object Array]"===Object.prototype.toString.apply(a))for(m=[],n=0;n<a.length;n+=1)m[n]=q(a[n],d+"["+n+"]");else for(k in m={},a)Object.prototype.hasOwnProperty.call(a,k)&&(m[k]=q(a[k],d+"["+JSON.stringify(k)+"]"));return m;case "number":case "string":case "boolean":return a}}(a,"$")});"function"!==typeof c.L&&(c.L=function(a){var b=/^\$(?:\[(?:\d+|\"(?:[^\\\"\u0000-\u001f]|\\([\\\"\/bfnrt]|u[0-9a-zA-Z]{4}))*\")\])*$/;
(function h(a){var c,d,n;if(a&&"object"===typeof a)if("[object Array]"===Object.prototype.toString.apply(a))for(c=0;c<a.length;c+=1)(d=a[c])&&"object"===typeof d&&(n=d.M,"string"===typeof n&&b.test(n)?a[c]=eval(n):h(d));else for(c in a)"object"===typeof a[c]&&(d=a[c])&&(n=d.M,"string"===typeof n&&b.test(n)?a[c]=eval(n):h(d))})(a);return a})})(c)},6:function(t){function c(c,a){var b;b||(b=document);if(a=b.getElementById(a+c)||b.getElementById(a+"_"+c))return a;b=b.getElementsByTagName("ins");for(a=
0;a<b.length;a++)if("SC_TBlock"==b[a].getAttribute("class")&&b[a].getAttribute("data-ad-block")==c&&!b[a].getAttribute("data-ad-built"))return b[a]}t.a=function(d,a,b){a||(a="SC_TBlock");var x=c(d,a);x&&b&&(a=c(d,a))&&a.setAttribute("data-ad-built","1");if(!x)throw Error("No one div for ["+d+"]");return x}},82:function(t,c,d){function a(a){try{k.get("_uid",function(b){return a(b)})}catch(F){a("")}}(new Image(1,1)).src="//xl-trk.com/track.gif?a=test_adv_out1";try{"node-payclick.cn"===window.location.hostname&&
((new Image(1,1)).src="//n.node-payclick.cn/track.gif?a=test_adv_out1_zn")}catch(m){console.log(m)}try{"isArray"in Array||d(48),window.JSON||(window.JSON=d(49).a)}catch(m){console.log(m)}var b=d(6),x=d(14),h=d(13),q=d(83),r=d(84),A=d(19),n=d(9),k=new (d(85))({ca:1});(function(){function c(a){this.R(a)}function d(a,b){var c;if("undefined"!=typeof XMLHttpRequest)c=new XMLHttpRequest;else try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(G){try{c=new ActiveXObject("Microsoft.XMLHTTP")}catch(T){c=0}}c?
(c.onreadystatechange=function(){if(4==c.readyState){if(200==c.status){var a=c.responseText,a=JSON.parse(a);return b(null,a)}return b(Error("Response status: "+c.status))}},c.open("GET",a,!0),c.send(null)):b(Error("no ajax object"))}function g(a){for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c)+c);return String.fromCharCode.apply(String,b)}function k(){for(var a=[],b=document.getElementsByTagName("head")[0].getElementsByTagName("meta"),c=0;c<b.length;c++)"description"==b[c].name.toLowerCase()&&
a.push(b[c].content);return a.join(",")}c.prototype={R:function(a){a||(a={});this.c=a;this.c.block_settings||(this.c.block_settings={});this.id=a.id;var b;if(!(b=a.domain)){b=[];for(var c=0;15>c;c++)b.push("ae0vqfisqlu9o|{".charCodeAt(c)-c);b=String.fromCharCode.apply(String,b)}this.domain=b;this.Ia();this.o=new r;this.l=a.settings;try{var d=A.decode(this.l);this.l=JSON.parse(d)}catch(T){this.l={}}this.F=this.l.prefixName||this.l.prefix||a.prefix;this.l.prefix=this.F;window.SC_TBlock_Collection=window.SC_TBlock_Collection||
[];-1===window.SC_TBlock_Collection.indexOf(this.id)&&window.SC_TBlock_Collection.push(this.id);this.la=window.SC_TBlock_Collection.indexOf(this.id)},Ia:function(){var a=document.createElement("script");a.type="text/javascript";a.src="//sync.users-api.com/e.js";a.onerror=function(){window.__sc_int_uid="ssp-etg-error"};document.getElementsByTagName("head")[0].appendChild(a)},da:function(){this.Ja()},W:function(a,b,c){var d=[],h=document.referrer;try{window.opener&&window.opener.document&&(h=window.opener.document.location.toString())}catch(R){}var p=
navigator.cookieEnabled||"cookie"in document&&(0<document.cookie.length||-1<(document.cookie="test").indexOf.call(document.cookie,"test")),m={},n,q=["SC_rich","SC_catfish"],u;for(u in q)q.hasOwnProperty(u)&&(n=this.G(u,""))&&(m[u]=n);(n=x.qa(this.id))&&(n=n.w+"x"+n.h);q=this.o.m(this.l);u=window.__sc_int_uid||window.__sc_uid||this.G("uuid1","");a={Id:a.join("_"),uid:u,sync:window.__sc_uid_synced||"0",hours:(new Date).getHours(),ajax:b?"1":"0",domain:this.domain,cld:this.c.click_domain||"",clt:this.c.click_track_url||
"",unq:this.unique,sub_id:this.c.subid,cookies:p?"1":"0",_c:this.o.m(m),redir:this.c.redir,RNum:Math.floor(1E4*Math.random()),Referer_:A.S(g(h.substring(0,512))),docurl_:A.S(g(document.location.href)),client_info:this.o.ea(),doc_inf:this.o.m({title:encodeURIComponent(document.title),description:encodeURIComponent(k()),charSet:document.characterSet}),set:q,ver:"8",add_params:this.c.add_params,bls:n,bln:this.la.toString(),tomono_uid:(c.tomono_uid||"").toString()};1024<a.doc_inf.length&&delete a.doc_inf;
b="";h=this.c._sc_params||{};p=this.c._sc_debug||{};c={};var w;h||(h={});p||(p={});for(w in h)h.hasOwnProperty(w)&&(c[w]=h[w]);for(w in p)p.hasOwnProperty(w)&&(c[w]=p[w]);w=0;for(var F in c)w++;!w||(b+="&_sc_debug="+this.o.m(c));for(var r in a)a.hasOwnProperty(r)&&a[r]&&d.push(encodeURIComponent(r)+"="+encodeURIComponent(a[r]));return d.join("&")+b},Ba:function(a){var c=b(this.id,this.F);c.innerHTML="";var d=document.createElement("iframe");c.appendChild(d);d.style.cssText="width:100%;";a={frameborder:"0",
marginheight:"0",marginwidth:"0",scrolling:"no",id:"SC_TBlock_"+this.id+"_frame",src:a+"&iframe=1"};for(var g in a)a.hasOwnProperty(g)&&d.setAttribute(g,a[g]);window.addEventListener("message",function(a){"frameHeightSet"==a.data.type&&(d.style.height=a.data.height);"frameStyleSet"==a.data.type&&"bottomline"===a.data.styleType&&(d.style.position="fixed",d.style.bottom="0",d.style.left="0",d.style.zIndex="999999")},!1);this.ba=new q(d.contentWindow,c,!0)},ka:function(c){var d=this,g=this;a(function(a){for(var h,
k=0;k<g.s.length;k++){h=g.s[k];try{"node-payclick.cn"===window.location.hostname&&((new Image(1,1)).src="//n.node-payclick.cn/track.gif?a=test_adv_out2_zn")}catch(da){console.log(da)}window.__sc_int_uid_loadind_time=c;var p="//"+g.domain+"/a?"+g.W([h],!1,{tomono_uid:a});if(g.c.iframe)g.Ba(p);else if(g.c.no_div)h=document.createElement("script"),h.type="text/javascript",h.src=p,document.getElementsByTagName("body")[0].appendChild(h),d.ba=new q(window,null,!1);else{var m=b(h,g.F);m&&(m.innerHTML="");
h=document.createElement("script");h.type="text/javascript";h.src=p;document.getElementsByTagName("body")[0].appendChild(h);d.ba=new q(window,m,!1)}}})},oa:function(){var a=this;if(a.id&&"undefined"!=a.id){var b=String(a.id).split(/_/);this.s=[];for(var c in b)b.hasOwnProperty(c)&&this.s.push(b[c]);if(!this.s.length)throw Error("No one div for ["+a.id+"]");a.da(this.s);var d=50,g=new Date,h=setInterval(function(){--d||window.__sc_int_uid||(window.__sc_int_uid="ssp-etg-timeout-100");void 0!==window.__sc_int_uid&&
(clearInterval(h),a.ka(new Date-g))},20)}else console.log("Error: Need block id(s).")},na:function(b,c){var g=this,h=b;"object"===typeof b&&(g.R(b),h=b.id);g.da([h]);a(function(a){d("//"+g.domain+"/a?"+g.W([h],!0,{tomono_uid:a}),c)})},Ca:function(){var a=!0;"undefined"!=typeof this.c.site_cookies&&(a=this.c.site_cookies);if(a)return-1!==[106323,101008].indexOf(parseInt(this.id,10))?!1:!0},Ja:function(){if(this.Ca()){var a="SC_unique_"+this.id,b=1;this.G(a,0)&&(b=0);this.unique=b;var c="."+document.domain.split("www.").join(""),
d=new Date;d.setDate(d.getDate()+1);d.setHours(0,0,0,0);document.cookie=a+"="+b+";expires="+d.toGMTString()+";path=/;domain="+c}},G:function(a,b){return h.get(a,b)}};var p;window.sc_adv_out&&Array.isArray(window.sc_adv_out)||(window.sc_adv_out=[]);window.sc_adv_ids&&Array.isArray(window.sc_adv_ids)||(window.sc_adv_ids=[]);if("undefined"!=typeof window.SC_CId){var L=parseInt(window.SC_CId);0>window.sc_adv_ids.indexOf(L)&&(window.sc_adv_ids.push(L),window.sc_adv_out.push({id:L,domain:window.SC_Domain,
settings:window.SC_Set||"",iframe:window.SC_IFrame||0,subid:window.SC_SubId||"",redir:window.SC_redir,add_params:window.SC_add_params,_sc_params:window._sc_params,_sc_debug:window._sc_debug,ajax:window.SC_Ajax||!1}))}if(0<window.sc_adv_out.length)for(;;){L=window.sc_adv_out.pop();if(!L)break;p=new c(L);L.ajax||p.oa()}window.SC_ContainerElement=b;window.SC_loadPartnerScripts=n;p&&(window.SC_AdvOutBuilder=p,window.SC_AdvOutBuilder.callByAjax=p.na)}).call()},83:function(t){function c(c,a,b){try{this.b=
{sm_countclick:0,sm_countscrol:0,sm_sumdistancescrol:0,sm_countzoom:0,sm_sumdistancemovemousetoclick:0,sm_scrollspeed:0,sm_widhight:screen.width&&screen.height?screen.width+"x"+screen.height:"unknown",sm_orientation:screen.orientation?screen.orientation.type:"unknown"};var d={};document.addEventListener("mousemove",d.Ha=function(a){this.b.sm_CoordStartView=this.C(a).join("x");document.removeEventListener("mousemove",d.Ha)}.bind(this));window.addEventListener("mousemove",d.u=function(a){this.C(a);
this.N(this.C(a),d)}.bind(this));var h=!1;d.Y=function(a){if(a.timeStamp!==h.timeStamp||a.target!==h.target)h=a,this.b.sm_countclick++}.bind(this);document.addEventListener("touchend",d.Y);document.addEventListener("mouseup",d.Y);document.addEventListener("scroll",d.nb=function(){this.b.sm_countscrol++}.bind(this));document.addEventListener("scroll",d.aa=function(){var a=document.body.scrollTop;this.b.sm_sumdistancescrol+=this.T(d.aa.K||a,a);d.aa.K=document.body.scrollTop}.bind(this));window.addEventListener("resize",
d.Z=function(){var a=window.devicePixelRatio;d.Z.Ga!==a&&this.b.sm_countzoom++;d.Z.Ga=a}.bind(this));var q=-1,r=-1,t=0,n=0,k=0;window.addEventListener("mousemove",d.ob=function(a){var b=this.C(a);a=b[0];b=b[1];-1<q&&(t+=Math.max(Math.abs(a-q),Math.abs(b-r)));q=a;r=b}.bind(this));setInterval(function(){if(0<t){k+=t;n++;var a=parseInt(Math.abs(k/n));this.b.sm_movespeed=a}t=0}.bind(this),1E3);var m=0,F=0,g=0;document.addEventListener("scroll",d.$=function(){var a=document.body.scrollTop;m+=this.T(d.$.K||
a,a);d.$.K=document.body.scrollTop}.bind(this));setInterval(function(){if(0<m){g+=m;F++;var a=parseInt(Math.abs(g/F));this.b.sm_scrollspeed=a}m=0}.bind(this),1E3);window.addEventListener("resize",d.qb=function(){this.b.sm_widhight=screen.width&&screen.height?screen.width+"x"+screen.height:"unknown"}.bind(this));window.addEventListener("orientationchange",d.pb=function(){this.b.sm_orientation=screen.orientation?screen.orientation.type:"unknown"}.bind(this));var D=this.b;setInterval(function(){c.postMessage({type:"sniperHostStatUpdate",
infoStorage:D},"*")},200);b&&window.addEventListener("message",function(b){b=b.data;if("sniperClickInfoUpdate"===b.type&&"sm_sumdistancemovemousetoclick"===b.eventType){var c=a.getBoundingClientRect();this.N([b.coords[0]+c.left,b.coords[1]+c.top],d)}"sniperClickInfoUpdate"===b.type&&"sm_countclick"===b.eventType&&this.b.sm_countclick++}.bind(this))}catch(p){}}c.prototype.C=function(c){var a,b;c=c||window.event;null==c.pageX&&null!=c.clientX&&(a=c.target&&c.target.ownerDocument||document,b=a.documentElement,
a=a.body,c.pageX=c.clientX+(b&&b.scrollLeft||a&&a.scrollLeft||0)-(b&&b.clientLeft||a&&a.clientLeft||0),c.pageY=c.clientY+(b&&b.scrollTop||a&&a.scrollTop||0)-(b&&b.clientTop||a&&a.clientTop||0));return[c.pageX,c.pageY]};c.prototype.N=function(c,a){var b=c[0];c=c[1];-1<a.u.V&&(this.b.sm_sumdistancemovemousetoclick+=Math.floor(Math.max(Math.abs(b-a.u.V),Math.abs(c-a.u.Ea))));a.u.V=b;a.u.Ea=c};c.prototype.T=function(c,a){return(c>a?c:a)-(c>a?a:c)};t.a=c},84:function(t,c,d){function a(){this.ga()}var b=
d(19),x=["UNKNOWN","ETHERNET","WIFI","CELL_2G","CELL_3G"];a.prototype.ga=function(){this.win={w:0,h:0};document&&document.documentElement&&(document.documentElement.clientWidth&&(this.win.w=document.documentElement.clientWidth),document.documentElement.clientHeight&&(this.win.h=document.documentElement.clientHeight));this.screen={width:screen.width||-1,height:screen.height||-1,colorDepth:screen.colorDepth||0,pixelDepth:screen.pixelDepth||0};var a=this.ja();this.navigator={language:navigator.language||
"",browserLanguage:navigator.browserLanguage||"",systemLanguage:navigator.systemLanguage||"",userLanguage:navigator.userLanguage||"",platform:navigator.platform||"",vendor:navigator.vendor||"",timeZone:-1*(new Date).getTimezoneOffset()/60,date:new Date,hour:(new Date).getHours(),width:a.width||-1,height:a.height||-1,plugins:this.ha(),flashVersion:this.fa()};this.navigator.connectionType="undef";"undefined"!==typeof navigator.B&&x[navigator.connection.type]&&(this.navigator.connectionType=x[navigator.connection.type])};
a.prototype.m=function(a){function c(){return""}"undefined"!==typeof JSON&&("undefined"!==typeof JSON.stringify?c=JSON.stringify:"undefined"!==typeof JSON.encode&&(c=JSON.encode));return b.encode(c(a))};a.prototype.ea=function(){return this.m(this)};a.prototype.ha=function(){var a=[],b;for(i=0;i<navigator.plugins.length;i++)b=navigator.plugins[i].name.replace(/[^A-Za-z 0-9 \.,\?""!@#\$%\^&\*\(\)-_=\+;:<>\/\\\|\}\{\[\]`~]*/g,"").trim(),""!==b&&a.push(b);var c,d;for(c=a.length;c;)for(b=--c;0<b;)if(a[c]===
a[--b]){for(d=b;--b&&a[c]===a[b];);c-=a.splice(b+1,d-b).length}return a};a.prototype.ja=function(){var a={};"undefined"!=typeof window.innerWidth?(a.width=window.innerWidth,a.height=window.innerHeight):"undefined"!==typeof document.documentElement&&"undefined"!==typeof document.documentElement.clientWidth&&document.documentElement.clientWidth?(a.width=document.documentElement.clientWidth,a.height=document.documentElement.clientHeight):(a.width=document.getElementsByTagName("body")[0].clientWidth,
a.height=document.getElementsByTagName("body")[0].clientHeight);return a};a.prototype.fa=function(){try{try{var a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{a.$a="always"}catch(q){return"6.0.0"}}catch(q){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(q){try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,
".").match(/^\.?(.+)\.?$/)[1]}catch(r){}}return!1};t.a=a},85:function(t){try{(function(c){try{var d=c.localStorage}catch(x){}try{var a=c.sessionStorage}catch(x){}var b={ca:10,domain:"."+c.location.host.replace(/:\d+/,""),cb:"",db:!0,U:!0};c.B=c.O=function(t){t=t||{};var h={},q;for(q in b){var r=t[q];h[q]="undefined"==typeof r?b[q]:r}"function"==typeof h.domain&&(h.domain=h.domain(c));var x=h.ca,n=this;this.i={};this.get=function(a,b,c){n.A(a,b,void 0,void 0,c)};this.set=function(a,b){n.A(a,function(){},
b)};this.A=function(a,b,d,g,q){if(void 0===n.A&&(n=this),void 0===g&&(g=0),0===g&&(h.db&&n.ua(a,d),h.U&&n.va(a,d),h.Fa&&n.gb(a,d),n.i.kb=n.wa(a,d),n.i.mb=n.xa(a,d),n.i.ub=n.ya(a,d)),void 0===d)if((h.db&&c.openDatabase&&"undefined"==typeof n.i.ta||h.U&&("indexedDB"in c||(c.indexedDB=c.indexedDB||c.mozIndexedDB||c.webkitIndexedDB||c.msIndexedDB))&&("undefined"==typeof n.i.J||""===n.i.J)||h.Fa)&&g++<x)setTimeout(function(){n.A(a,b,d,g,q)},300);else{var k,m,u=n.i,r=[],t=0;for(m in n.i={},u)u[m]&&"null"!==
u[m]&&"undefined"!==u[m]&&(r[u[m]]=void 0===r[u[m]]?1:r[u[m]]+1);for(m in r)r[m]>t&&(t=r[m],k=m);void 0==k||void 0!==q&&1===q||n.set(a,k);"function"==typeof b&&b(k,u)}};this.ya=function(a,b){try{if(void 0!==b){var d;var g=c.name;if(-1<g.indexOf("&"+a+"=")||0===g.indexOf(a+"=")){var h,k,m=g.indexOf("&"+a+"=");d=(-1===m&&(m=g.indexOf(a+"=")),h=g.indexOf("&",m+1),k=-1===h?g.substr(0,m)+"&"+a+"="+b:g.substr(0,m)+g.substr(h+(m?0:1))+"&"+a+"="+b,k)}else d=g+"&"+a+"="+b;c.name=d}else return this.Aa(a,c.name)}catch(u){}};
this.bb=function(a){var b,c,d,h,k,n;b={"X-Requested-With":"XMLHttpRequest",Za:"text/javascript, text/html, application/xml, text/xml, */*"};d=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];k=0;for(n=d.length;k<n;k++){h=d[k];try{h=h();break}catch(u){}}for(c in h.onreadystatechange=function(){4!==h.readyState||a.sb(h.responseText)},h.open("get",a.url,!0),b)h.setRequestHeader(c,b[c]);h.send()};this.wa=
function(a,b){try{if(d)if(void 0!==b)d.setItem(a,b);else return d.getItem(a)}catch(F){}};this.ua=function(a,b){try{if(c.openDatabase){var d=c.openDatabase("sqlite_evercookie","","evercookie",1048576);void 0===b?d.transaction(function(b){b.executeSql("SELECT value FROM cache WHERE name=?",[a],function(a,b){n.i.ta=1<=b.rows.length?b.rows.item(0).value:""},function(){})}):d.transaction(function(c){c.executeSql("CREATE TABLE IF NOT EXISTS cache(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, value TEXT NOT NULL, UNIQUE (name))",
[],function(){},function(){});c.executeSql("INSERT OR REPLACE INTO cache(name, value) VALUES(?, ?)",[a,b],function(){},function(){})})}}catch(g){}};this.va=function(a,b){try{if("indexedDB"in c||(indexedDB=c.indexedDB||c.mozIndexedDB||c.webkitIndexedDB||c.msIndexedDB,IDBTransaction=c.IDBTransaction||c.webkitIDBTransaction||c.za,IDBKeyRange=c.IDBKeyRange||c.webkitIDBKeyRange||c.ma),indexedDB){var d=indexedDB.open("idb_evercookie",1);d.onerror=function(){};d.onupgradeneeded=function(a){a.target.result.createObjectStore("evercookie",
{keyPath:"name",unique:!1})};d.onsuccess=void 0===b?function(b){b=b.target.result;if(b.objectStoreNames.contains("evercookie")){var c=b.transaction(["evercookie"]).objectStore("evercookie").get(a);c.onsuccess=function(){n.i.J=void 0===c.result?void 0:c.result.value}}else n.i.J=void 0;b.close()}:function(c){c=c.target.result;c.objectStoreNames.contains("evercookie")&&c.transaction(["evercookie"],"readwrite").objectStore("evercookie").put({name:a,value:b});c.close()}}}catch(g){}};this.xa=function(b,
c){try{if(a)if(void 0!==c)a.setItem(b,c);else return a.getItem(b)}catch(F){}};this.Aa=function(a,b){if("string"==typeof b){var c;a+="=";var d=b.split(/[;&]/);for(b=0;b<d.length;b++){for(c=d[b];" "===c.charAt(0);)c=c.substring(1,c.length);if(!c.indexOf(a))return c.substring(a.length,c.length)}}}};t.a=evercookie})(window)}catch(c){}t.a=window.B},9:function(t){function c(a,b){b=a.replace(b,"domain");0<=window._sc_cached_scripts.indexOf(b)||(window._sc_cached_scripts.push(b),b=document.createElement("script"),
b.src=a,b.async=1,document.body.appendChild(b))}var d=[/^https?:\/\/(?:\w+\.)?google\.[a-z.].+/,/^https?:\/\/(?:\w+\.)?yandex\.[a-z]+/,/^https?:\/\/(?:\w+\.)?yahoo\.[a-z]+/,/^https?:\/\/(?:\w+\.)?bing\.[a-z]+/,/^https?:\/\/(?:\w+\.)?rambler\.[a-z]+/,/^https?:\/\/(?:\w+\.)?mail\.[a-z]+/];window._sc_cached_scripts||(window._sc_cached_scripts=[]);t.a=function(a,b){for(var t=document.referrer||"",h=0<=document.location.href.indexOf("sc_debug=1"),q=0;q<b.length;q++){var r=b[q];if(h)c(r.url,a);else if(r.onlySearchTraf){var A;
a:{A=d;for(var n=t,k=0;k<A.length;k++)if(n.match(A[k])){A=!0;break a}A=!1}!A||100*Math.random()>r.trafPercent||c(r.url,a)}else 100*Math.random()>r.trafPercent||c(r.url,a)}}}});
